version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis-stack
      - database
      - scraper
    environment:
      - REDIS_HOST=redis-stack # Corregido: debe coincidir con el nombre del servicio
      - DB_HOST=database

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"

  scraper:
    build: ./scraper
    container_name: scraper
    ports:
      - "5000:5000"
    command: python ./scraper.py
    depends_on:
      - database

  database:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: waze
      MONGO_INITDB_ROOT_USERNAME: HM
      MONGO_INITDB_ROOT_PASSWORD: colocolo123
    volumes:
      - mongodata:/data/db
      #- ./base.js:/docker-entrypoint-initdb.d/base.js # Script de inicialización

volumes:
  mongodata:
    driver: local
#docker-compose up --build
